name: CI/CD Microservices
##
on:
  push:
    branches:
      - main
    paths:
      - "*/**"         # catch all service dirs
      - "helm-charts/**"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Detect Changed Services
        id: changes
        run: |
          CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || git ls-tree --name-only -d HEAD)
          # Only pick Project-01 subdirectories
          CHANGED_DIRS=$(echo "$CHANGED_DIRS" | grep '^Project-01/' | cut -d/ -f2 | sort -u)
          # Convert to comma-separated list
          CHANGED_DIRS=$(echo "$CHANGED_DIRS" | tr '\n' ',' | sed 's/,$//')
          echo "Changed dirs: $CHANGED_DIRS"
          echo "changed=$CHANGED_DIRS" >> $GITHUB_OUTPUT

      - name: Debug changed services
        run: |
          echo "Changed services: ${{ steps.changes.outputs.changed }}"

      - name: Build & Push Images
        run: |
          IFS=',' read -ra SVCS <<< "${{ steps.changes.outputs.changed }}"
          for svc in "${SVCS[@]}"; do
            DOCKER_PATH="Project-01/$svc"
            if [ -f "$DOCKER_PATH/Dockerfile" ]; then
              IMAGE="${{ vars.DOCKERHUB_USERNAME }}/$svc:${GITHUB_SHA::7}"
              echo "🚀 Building and pushing $IMAGE"
              docker build -t $IMAGE $DOCKER_PATH
              docker push $IMAGE

              # Update Helm values.yaml if chart exists
              HELM_VALUES="helm-charts/$svc/values.yaml"
              if [ -f "$HELM_VALUES" ]; then
                sed -i "s|repository:.*|repository: ${{ vars.DOCKERHUB_USERNAME }}/$svc|g" "$HELM_VALUES"
                sed -i "s|tag:.*|tag: ${GITHUB_SHA::7}|g" "$HELM_VALUES"
              fi
            fi
          done

      - name: Commit Helm Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add helm-charts/
          git commit -m "Update image tags [skip ci]" || echo "No changes to commit"
          git push
